updates cronjob config

diff --git a/modules/signoz-fluxcd/templates/clickhouse-backup-patch.yaml b/modules/signoz-fluxcd/templates/clickhouse-backup-patch.yaml
--- a/modules/signoz-fluxcd/templates/clickhouse-backup-patch.yaml
+++ b/modules/signoz-fluxcd/templates/clickhouse-backup-patch.yaml
@@ -1,30 +1,136 @@
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: clickhouse-backup-config
+  namespace: signoz-fluxcd
+data:
+  backup_disk.xml: |
+    <clickhouse>
+        <storage_configuration>
+            <disks>
+                <s3>
+                    <type>s3</type>
+                    <endpoint>https://s3.us-east-1.amazonaws.com</endpoint>
+                    <use_environment_credentials>1</use_environment_credentials>
+                    <region>us-east-1</region>
+                </s3>
+            </disks>
+        </storage_configuration>
+        <backups>
+            <remote>
+                <type>disk</type>
+                <disk>s3</disk>
+                <path>clickhouse-backup-{$aws_account_id}</path>
+            </remote>
+        </backups>
+    </clickhouse>
+---
 apiVersion: batch/v1
 kind: CronJob
 metadata:
-  name: clickhouse-backup
+  name: clickhouse-backup-cron
+  namespace: signoz-fluxcd
 spec:
   schedule: "0 0 * * *"
-  concurrencyPolicy: Forbid
-  successfulJobsHistoryLimit: 3
-  failedJobsHistoryLimit: 1
+  concurrencyPolicy: "Forbid"
   jobTemplate:
     spec:
+      backoffLimit: 1
       template:
+        metadata:
+          labels:
+            app: clickhouse-backup-cron
         spec:
-          containers:
-          - name: clickhouse-backup
-            image: aws/aws-cli:2.8.12
-            command:
-            - /bin/sh
-            - -c
-            - |
-              aws s3 mb s3://clickhouse-backup-${aws_account_id}
-              aws s3 sync /data/clickhouse-backup s3://clickhouse-backup-${aws_account_id}
-            volumeMounts:
-            - name: backup-data
-              mountPath: /data/clickhouse-backup
-          volumes:
-          - name: backup-data
-            emptyDir: {}
           serviceAccountName: clickhouse-backup-service-account
-          restartPolicy: OnFailure
+          restartPolicy: Never
+          containers:
+            - name: run-backup-cron
+              image: clickhouse/clickhouse-client:latest
+              imagePullPolicy: IfNotPresent
+              env:
+                - name: CLICKHOUSE_SERVICES
+                  value: "signoz-clickhouse"
+                - name: CLICKHOUSE_PORT
+                  value: "9000"
+                - name: BACKUP_USER
+                  valueFrom:
+                    secretKeyRef:
+                      name: clickhouse-admin-password
+                      key: username
+                - name: BACKUP_PASSWORD
+                  valueFrom:
+                    secretKeyRef:
+                      name: clickhouse-admin-password
+                      key: password
+                - name: MAKE_INCREMENT_BACKUP
+                  value: "1"
+                - name: FULL_BACKUP_WEEKDAY
+                  value: "1"
+              command:
+                - bash
+                - -ec
+                - |
+                  CLICKHOUSE_SERVICES=$(echo $CLICKHOUSE_SERVICES | tr "," " ");
+                  BACKUP_DATE=$(date +%Y-%m-%d-%H-%M-%S);
+                  declare -A BACKUP_NAMES;
+                  declare -A DIFF_FROM;
+                  if [[ "" != "$BACKUP_PASSWORD" ]]; then
+                    BACKUP_PASSWORD="--password=$BACKUP_PASSWORD";
+                  fi;
+                  for SERVER in $CLICKHOUSE_SERVICES; do
+                    if [[ "1" == "$MAKE_INCREMENT_BACKUP" ]]; then
+                      LAST_FULL_BACKUP=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '%${SERVER}%' AND name LIKE '%full%' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
+                      TODAY_FULL_BACKUP=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '%${SERVER}%' AND name LIKE '%full%' AND desc NOT LIKE 'broken%' AND toDate(created) = today() ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD)
+                      PREV_BACKUP_NAME=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
+                      DIFF_FROM[$SERVER]="";
+                      if [[ ("$FULL_BACKUP_WEEKDAY" == "$(date +%u)" && "" == "$TODAY_FULL_BACKUP") || "" == "$PREV_BACKUP_NAME" || "" == "$LAST_FULL_BACKUP" ]]; then
+                        BACKUP_NAMES[$SERVER]="full-$BACKUP_DATE";
+                      else
+                        BACKUP_NAMES[$SERVER]="increment-$BACKUP_DATE";
+                        DIFF_FROM[$SERVER]="--diff-from-remote=$PREV_BACKUP_NAME";
+                      fi
+                    else
+                      BACKUP_NAMES[$SERVER]="full-$BACKUP_DATE";
+                    fi;
+                    echo "set backup name on $SERVER = ${BACKUP_NAMES[$SERVER]}";
+                  done;
+                  for SERVER in $CLICKHOUSE_SERVICES; do
+                    echo "create ${BACKUP_NAMES[$SERVER]} on $SERVER";
+                    clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('create ${SERVER}-${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
+                  done;
+                  for SERVER in $CLICKHOUSE_SERVICES; do
+                    while [[ "in progress" == $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='create ${SERVER}-${BACKUP_NAMES[$SERVER]}' FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; do
+                      echo "still in progress ${BACKUP_NAMES[$SERVER]} on $SERVER";
+                      sleep 1;
+                    done;
+                    if [[ "success" != $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='create ${SERVER}-${BACKUP_NAMES[$SERVER]}' FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; then
+                      echo "error create ${BACKUP_NAMES[$SERVER]} on $SERVER";
+                      clickhouse-client -mn --echo -q "SELECT status,error FROM system.backup_actions WHERE command='create ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
+                      exit 1;
+                    fi;
+                  done;
+                  for SERVER in $CLICKHOUSE_SERVICES; do
+                    echo "upload ${DIFF_FROM[$SERVER]} ${BACKUP_NAMES[$SERVER]} on $SERVER";
+                    clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
+                  done;
+                  for SERVER in $CLICKHOUSE_SERVICES; do
+                    while [[ "in progress" == $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; do
+                      echo "upload still in progress ${BACKUP_NAMES[$SERVER]} on $SERVER";
+                      sleep 5;
+                    done;
+                    if [[ "success" != $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; then
+                      echo "error ${BACKUP_NAMES[$SERVER]} on $SERVER";
+                      clickhouse-client -mn --echo -q "SELECT status,error FROM system.backup_actions WHERE command='upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
+                      exit 1;
+                    fi;
+                    clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('delete local ${SERVER}-${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
+                  done;
+                  echo "BACKUP CREATED"
+              volumeMounts:
+                - name: backup-config
+                  mountPath: /etc/clickhouse-server/config.d/backup_disk.xml
+                  subPath: backup_disk.xml
+          volumes:
+            - name: backup-config
+              configMap:
+                name: clickhouse-backup-config
